'use client';
// @ts-nocheck

import React, { useRef, useState } from 'react';
import { Download, Upload, RotateCcw, AlertTriangle, CheckCircle2, FileCode } from 'lucide-react';
import { AppSettings, VolunteerProfile } from '../../types';

interface DataBackupSettingsProps {
  settings: AppSettings;
  profile: VolunteerProfile;
  onRestoreSettings: (restored: AppSettings) => void;
  onRequestResetDefaults: () => void;
}

export const DataBackupSettings: React.FC<DataBackupSettingsProps> = ({
  settings,
  profile,
  onRestoreSettings,
  onRequestResetDefaults
}) => {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [importStatus, setImportStatus] = useState<string | null>(null);

  const handleExportData = () => {
    const exportBundle = {
      exportDate: new Date().toISOString(),
      volunteer: {
        id: profile.id,
        name: profile.name,
        email: profile.email,
        totalHours: profile.totalHours,
        impactScore: profile.impactScore,
        location: profile.location,
        joinDate: profile.joinDate
      },
      settings,
      version: '2.5-production'
    };

    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(exportBundle, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `volunteer_settings_backup_${profile.id}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const parsed = JSON.parse(event.target?.result as string);
        if (parsed.settings && typeof parsed.settings === 'object') {
          onRestoreSettings({
            ...settings,
            ...parsed.settings
          });
          setImportStatus('Successfully restored settings from backup archive!');
        } else if (parsed.travelRadiusMiles !== undefined) {
          // Direct settings object
          onRestoreSettings({
            ...settings,
            ...parsed
          });
          setImportStatus('Successfully imported configuration file!');
        } else {
          setImportStatus('Invalid backup format. Ensure file was generated by this portal.');
        }
      } catch (err) {
        setImportStatus('Error reading file. Please provide a valid JSON configuration.');
      }
      setTimeout(() => setImportStatus(null), 4000);
    };
    reader.readAsText(file);
    // Reset file input value so user can re-upload if needed
    e.target.value = '';
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
      {/* Backup & Portability */}
      <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-xs space-y-4">
        <div className="flex items-center gap-2 pb-3 border-b border-slate-100">
          <Download className="w-4 h-4 text-emerald-700" />
          <h2 className="text-sm font-bold text-slate-900 uppercase tracking-wide">Data Portability & Export</h2>
        </div>

        <div className="space-y-3">
          <p className="text-xs text-slate-600 leading-relaxed">
            Download a complete portable archive of your volunteer profile, certified hours transcript, and system configuration.
          </p>

          <div className="p-4 bg-slate-50 border border-slate-200 rounded-xl space-y-3">
            <div className="flex items-center justify-between">
              <div className="text-xs font-bold text-slate-900">
                Export All Records (JSON Bundle)
              </div>
              <span className="text-[10px] uppercase font-bold text-emerald-700 bg-emerald-100 px-2 py-0.5 rounded">
                Portable
              </span>
            </div>
            <p className="text-[11px] text-slate-500">
              Includes {profile.totalHours} verified hours, milestone achievements, skills profile, and custom availability matrix.
            </p>
            <button
              type="button"
              onClick={handleExportData}
              className="w-full py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-semibold flex items-center justify-center gap-1.5 transition-colors shadow-xs"
            >
              <Download className="w-4 h-4" />
              <span>Download JSON Backup Archive</span>
            </button>
          </div>

          {/* Import Archive */}
          <div className="p-4 bg-slate-50 border border-slate-200 rounded-xl space-y-3">
            <div className="text-xs font-bold text-slate-900 flex items-center gap-1.5">
              <Upload className="w-3.5 h-3.5 text-slate-500" />
              <span>Restore from Backup JSON</span>
            </div>
            <p className="text-[11px] text-slate-500">
              Import a previously exported JSON settings file to restore custom scheduling parameters.
            </p>
            <input
              type="file"
              ref={fileInputRef}
              accept=".json"
              onChange={handleFileChange}
              className="hidden"
            />
            <button
              type="button"
              onClick={() => fileInputRef.current?.click()}
              className="w-full py-2 bg-white hover:bg-slate-100 text-slate-700 border border-slate-300 rounded-xl text-xs font-semibold flex items-center justify-center gap-1.5 transition-colors"
            >
              <FileCode className="w-4 h-4 text-slate-600" />
              <span>Select Backup File to Restore</span>
            </button>
            {importStatus && (
              <div className={`p-2.5 rounded-lg text-xs font-semibold ${
                importStatus.includes('Successfully') ? 'bg-emerald-50 text-emerald-800' : 'bg-red-50 text-red-800'
              }`}>
                {importStatus}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Cache Reset & Restore */}
      <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-xs space-y-4">
        <div className="flex items-center gap-2 pb-3 border-b border-slate-100">
          <RotateCcw className="w-4 h-4 text-amber-700" />
          <h2 className="text-sm font-bold text-slate-900 uppercase tracking-wide">Reset Preferences & Defaults</h2>
        </div>

        <div className="space-y-3">
          <p className="text-xs text-slate-600 leading-relaxed">
            Restore all system preferences back to their initial factory configurations without modifying or deleting your verified hours transcript.
          </p>

          <div className="p-4 bg-amber-50/60 border border-amber-200 rounded-xl space-y-3">
            <div className="flex items-center gap-2 text-amber-900 text-xs font-bold">
              <AlertTriangle className="w-4 h-4 text-amber-600" />
              <span>Reset Settings to Standard Values</span>
            </div>
            <p className="text-[11px] text-amber-800 leading-relaxed">
              Will reset travel radius (15 mi), quiet hours (21:30–07:30), max weekly hours (20h), and notification preferences to standard defaults.
            </p>
            <button
              type="button"
              onClick={onRequestResetDefaults}
              className="w-full py-2 bg-white hover:bg-amber-100/60 text-amber-900 border border-amber-300 rounded-xl text-xs font-semibold flex items-center justify-center gap-1.5 transition-colors"
            >
              <RotateCcw className="w-4 h-4 text-amber-700" />
              <span>Restore Default Settings</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
